
### List
GET https://localhost:7198/api/Category/get HTTP/1.1
content-type: application/json


### Create
POST https://localhost:7198/api/Category/add HTTP/1.1
content-type: application/json

{
  "name": "a{{$guid}}",
  "description": "string"
}


### Create
POST https://localhost:7198/api/Product/add HTTP/1.1
content-type: application/json

{
  "name": "a{{$guid}}",
  "description": "alexis",
  "price": 0,
  "stock": 0,
  "categoryId": "f98a2b33-ed39-4194-b920-22a5bec7684f"
}