
### List
GET https://localhost:7198/api/Category/get HTTP/1.1
content-type: application/json


### Create
POST https://localhost:7198/api/Category/add HTTP/1.1
content-type: application/json

{
  "name": "a{{$guid}}",
  "description": "string"
}


### Create
POST https://localhost:7198/api/Product/add HTTP/1.1
content-type: application/json

{
  "name": "a{{$guid}}",
  "description": "string",
  "price": 0,
  "stock": 0,
  "categoryId": "f9f0b7f1-c11d-4750-8a7a-e47c29dbc05f"
}